### ISSUE TITLE
Blank lines stripped after end of list

### ISSUE THREAD

**Issue by axefrog** [gingko/client#103]
![image](https://user-images.githubusercontent.com/298883/43351790-ec850034-925a-11e8-9598-bf56a50ef463.png)

![image](https://user-images.githubusercontent.com/298883/43351787-dcf14c86-925a-11e8-9305-2bf54216582c.png)

**Comment by pecefix** [comment]
My Workaround for this 'stripped blank lines' after bullet points is putting a Line Break HTML-Element in the next line
```
- includes an additional closing handshake in-band …
<br>

```
followed by a blank line.

**Comment by axefrog** [comment]
@pecefix Yeah I do the same

**Comment by AdrianoFerrari** [comment]
Thanks for workaround.

This is a quick fix, and will be implemented once I'm done with current priority of saving to files ( #105 ).
