### ISSUE TITLE
HTML export without FullStory

### ISSUE THREAD

**Issue by vladdu** [gingko/client#106]
I would prefer the exported HTML to be clean and without extra stuff, especially such that watches the user's actions.

**Comment by AdrianoFerrari** [comment]
Hi Vlad,

Are you referring to exports for the **online** version?
I'm not using FullStory on the desktop version.

The online version doesn't have a public repository, and it will be replaced by a later version of this one anyway.

**Comment by vladdu** [comment]
Yeah, sorry, I mixed them up, I see the desktop doesn't have that.
