### ISSUE TITLE
Add open windows to "Window" menu

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#112]
> Multiple windows opens: should be listed in the Window menu?

**Comment by SquidLord** [comment]
That should really be under View. There may be times you want to open multiple windows to the same file, if it happens to be particularly sprawling.

**Comment by AdrianoFerrari** [comment]
Thanks for the input.

Important question though: I wasn't aware that it was *possible* to open multiple windows to the same file yet... are you able to? If so, it's not an expected (therefore, not tested) feature.

**Comment by SquidLord** [comment]
Not that I can find at the moment. However, it's a common editing mode of
operation. Being able to split a frame and edit the same file side-by-side
or open multiple views/windows on a file and edit different sections at the
same time in order to keep them in synchrony.

**Comment by AdrianoFerrari** [comment]
Fixed in [v2.4.2](https://github.com/gingko/client/releases/tag/v2.4.2).
