### ISSUE TITLE
Vanishing Cards When Dragging and Dropping on Mac

### ISSUE THREAD

**Issue by crisedwards** [gingko/client#116]
I am on the desktop version on a Mac [Latest MacOS]. Sometimes when I am dragging and dropping cards to reorder them, I will drop a card on top of another card [I can't see whether the 'green glow' appears to signal where the card I am moving is going to land] and the card I am dropping onto another card just vanishes. As far as I can tell.

I thought maybe the card didn't vanish but ended up somewhere else, but I can not find the vanished card. Curious why there is no 'Find' feature to search all of the cards, either.

Thanks!

**Comment by AdrianoFerrari** [comment]
You're not having a good day with Gingko, it seems :frowning_face: . Sorry about this, @crisedwards !
I reopened the original issue where this came up, and will look into it.

Again, if you still can't see the card (even after close, quit, reopen), then send me the file, and some info on lost card, and I'll be able to recover it for you.

PS: If you're on latest Gingko, you should be able to search by clicking magnifying glass at top right.

**Comment by crisedwards** [comment]
Oh it's not in any bad faith. I love Gingko so I am just putting in things
I found. I've worked with Dev  teams so I just report all the things I find
so it can be fixed or improved.
