### ISSUE TITLE
Undo unavailable while editing on macOS?

### ISSUE THREAD

**Issue by crisedwards** [gingko/client#117]
There is no Undo feature, such as Command+Z on a Mac.

I had selected a big paragraph of text, meaning to copy it, but accidentally hit ENTER and the whole paragraph vanished with no way of bringing it back. :/

**Comment by AdrianoFerrari** [comment]
Oh no, @crisedwards :frowning: !

There is _supposed_ to be Undo when editing... in other words, as long as you don't git Cmd+Enter to save the changes, Cmd+Z should work. If it doesn't work then I must have introduced a bug in last release.

If the paragraph was saved **at least once**, it's still in the version history. **I can recover it** for you if you get in touch via in-app chat, and send me the file.

**Comment by AdrianoFerrari** [comment]
Should b fixed in [v2.4.2](https://github.com/gingko/client/releases/tag/v2.4.2)

**Comment by crisedwards** [comment]
Thanks, Adriano! :)

Hope you are doing well.
