### ISSUE TITLE
Export only a subtree, or only a given column

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#12]
**Current**: we can only export the entire tree.

**Desired**: ability to choose to export the following portions of a tree:
* Currently selected card & its subtree
* A given column

**Comment by AdrianoFerrari** [comment]
This is what I'm working on for Export:
![screenshot_2018-03-29_10-23-01](https://user-images.githubusercontent.com/323678/38094311-7420b076-333b-11e8-80be-eb055da69db9.png)

Left pane is the app as usual.
Right pane has export settings (along bottom), and live preview of the export at top.

I'm thinking for now, simple radio buttons and dropdowns to select what to export, and what format. But later, could do selections in the app view (click on which column to export, for example).

**Comment by Jos512** [comment]
That looks cool and certainly seems useful for plenty of users. :-)

But in my case I just want to export the current card and its children. I'd rather not start off with everything exported in a live preview, and then have to disable each card level to end up with the handful of cards I wanted to export. That are a lot of mouse clicks for something that could have been a keyboard shortcut.

**Comment by Jos512** [comment]
> How often do you imagine exporting? And at what points in the process do you imagine doing so?

In my case, the tree layout is roughly like:

~~~
Category > Topic > Rough draft > Blog post > subsections of post
~~~

I would export each blog posts individually so I can add it to the site. I would do that multiple times per week, once for each blog post. (So not all at once.)

'Problem' is just that Gingko is so versatile and flexible :smile: , so I'm not sure how useful my intended workflow approach is for others.

**Comment by AdrianoFerrari** [comment]
Yes, that's a common use case. Export "Current Card & Children", and "Column x" are the two most common in my experience.

I'll try to make sure it's easy and quick to do both, and that your previous choice is remembered (per-file). In your particular case for example: if you open your blog tree, it would be something like "Alt+F+E" and then "Enter" and "Enter" to export the `current+children`, in same directory as last export, with title = `{filename}-{current-card-title}.txt`

**Comment by AdrianoFerrari** [comment]
I'll move the "Export Live Preview" to a different issue. In the meantime, I've implemented these export options with a simple menu:
![screenshot_2018-03-31_08-47-57](https://user-images.githubusercontent.com/323678/38163346-861916e8-34c0-11e8-88aa-cc2eeee09d57.png)
