### ISSUE TITLE
Error when opening saved file

### ISSUE THREAD

**Issue by LeoTranGH** [gingko/client#125]
I am getting two errors when I try to open a saved file. 

First error: 
Unhandled Error
Error: net::ERR_SSL_PROTOCOL_ERROR

Second Error:
![image](https://user-images.githubusercontent.com/9096650/45183335-0685f380-b1e1-11e8-8238-0c9346ded08e.png)

**Comment by AdrianoFerrari** [comment]
Hi @LeoTranGH .

The second error was reported earlier, and I believe I fixed it with today's release. You can see discussion here:
#124 

If you are still experiencing the error after the app automatically updates to 2.2.3, please reopen that issue and make a comment there.

(to check the version you're running, open a new Blank file, and then do "Help > Open Debugging Tools > Console")
