### ISSUE TITLE
Linking broken on Markdown Reference Page

### ISSUE THREAD

**Issue by KenyanBurnham** [gingko/client#126]
Both links are broken on https://gingkoapp.com/markdown if you are looking for markdown syntax information. If you click on "Mastering Markdown" or "Markdown Syntax" you get a page that says:

"Cannot GET /designshack.net/articles/html/mastering-markdown-30-resources-apps-and-tutorials-to-get-you-started/"

**Comment by AdrianoFerrari** [comment]
Hi Kenyan. Thanks for the input!

That page isn't actually an official one... it's a user-generated public tree.

I don't think I linked to it anywhere in FAQ or other official docs... let me know if I'm mistaken.
