### ISSUE TITLE
Ctrl-Up/Down/Left/Right arrows on Windows don't open a new card in that direction when editing a card

### ISSUE THREAD

**Issue by SquidLord** [gingko/client#132]
Being able to hit Control-Arrow while editing a card to save the current card and open a new blank one in that direction is incredibly useful. As it stands you either have to use Control-J or Control-K to "split" up or down if you want to continuously add cards, but that breaks a lot of the navigation flow.

Control-Left doesn't necessarily need to be set, and I am not exactly sure what it should do even if you wanted to (open a new empty card to the left and down from the parent of the card that you're currently editing?).

**Comment by AdrianoFerrari** [comment]
This is intentional, since Ctrl+arrows are used by many to move back/forward by one word at a time when editing text.

Ctrl+J/K is a solution, but those aren't available on desktop (yet, #5), but it's likely the next thing I'll add, once I get past some recent bugs.

(FYI @SquidLord , this list of issues is *only* for the desktop version)

**Comment by SquidLord** [comment]
> (FYI @SquidLord , this list of issues is only for the desktop version... I mention this because you say that "as it stands, use Ctrl+J/K" which aren't available on desktop, so I wanted to clarify just in case)

Then for extra comedy value, this may come as a bit of a shock:

In Windows 10, Ctrl-J while editing a card actually opens a blank card beneath the one being edited and moves into it to edit, while Ctrl-K while editing opens one _above_. Likewise if you're not in editing mode for the card.

That is the _most_ implemented not-implemented-yet feature I've ever seen.

Now, it doesn't split the card there, which is probably what it should do, but it definitely creates one above and below.

**Comment by AdrianoFerrari** [comment]
> Then for extra comedy value, this may come as a bit of a shock
:stuck_out_tongue: You're right!

I forgot that I implemented "new card below/above" shortcuts from edit mode. Doesn't split, that's true, but at least saves a step: from "save, new card below" to "new card below".
