### ISSUE TITLE
Cannot install Gingko

### ISSUE THREAD

**Issue by Jos512** [gingko/client#142]
I tried to install Gingko on Windows 7 SP1, 64-bit. I downloaded the latest version [from the website](https://gingko.io/#download) (2.2.9) and got this error during installing:

![error_2018-12-11_17-40-21](https://user-images.githubusercontent.com/13403160/49815512-37d80780-fd6c-11e8-9be4-0205ba4aa171.png)

The same error happens when I try to launch the (partially?) installed app with the Gingko shortcut on the desktop.

---

Edit:

I could install version 2.2.5 with no problem, and the program itself seems to be running fine as well. If the error above is indeed caused by Gingko (and not Electron), then the issue seem to have happened [between these 2.2.5 and 2.2.9 commits](https://github.com/gingko/client/compare/v2.2.5...v2.2.9).

**Comment by AdrianoFerrari** [comment]
Thanks for letting me know, and for the detailed error message and tests.
Will look into this.

**Comment by AdrianoFerrari** [comment]
I was able to reproduce the error, and I believe I fixed it for 2.3.0.
Let me know if you're able to install it, @Jos512 

Thanks again!

**Comment by Jos512** [comment]
I had no troubles installing version 2.3.0. 

Thanks for the quick fix! :slightly_smiling_face:
