### ISSUE TITLE
Desktop installation path

### ISSUE THREAD

**Issue by Alex-T-H** [gingko/client#145]
In Windows 10 built 1809 the gingko version 2.3.2 installs into
C:\Users\MYUSERNAME\AppData\Local\Programs\gingko-client

This location is unusual for any program to install.

Suggestion: change install path to
C:\Program Files (x86)\gingko-client
and provide the installer with the option to choose the installation path during installation.

**Comment by Alex-T-H** [comment]
In Windows 10 built 1809 the gingko version 2.3.2 installs into
 C:\Users\MYUSERNAME\AppData\Local\Programs\gingko-client

This location is unusual for any program to install.

Suggestion: change install path to
 C:\Program Files (x86)\gingko-client
and provide the installer with the option to choose the installation path during installation.

**Comment by AdrianoFerrari** [comment]
Would like to be able to do this, but the installer setup seems buggy for now and often fails. Probably related to this issue:
https://github.com/electron-userland/electron-builder/issues/2907

Will label as won't-fix for now.
Might come back to this if that issue is resolved on their end.

**Comment by Alex-T-H** [comment]
That doesn't seem to be the point, see the discussion under
https://github.com/atom/atom/issues/7095

It is a design decision you take: use the installer as is or reprogram it to your liking. 

Installers are not too hard to (re-)program, it is just something a SW-designer usually doesn't do often in his life.

**Comment by Alex-T-H** [comment]
Hi Adriano,

I don't think it is a bug, see the discussion under
atom/atom#7095

It is a design decision you take: use the installer as is or reprogram it to your liking.

Installers are not too hard to (re-)program, it is just something a SW-designer usually doesn't do often in his life.
 
-------------------------------------------------------


On Thu, 07 Feb 2019 08:51:19 -0800
Adriano Ferrari <notifications@github.com> wrote:

> Would like to be able to do this, but the installer setup seems buggy for now and often fails. Probably related to this issue:
> https://github.com/electron-userland/electron-builder/issues/2907
> 
> Will label as won't-fix for now.
> Might come back to this if that issue is resolved on their end.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gingko/client/issues/145#issuecomment-461507393


-- 
Axel Hochgraef <a_hochgraef@hotmail.com>
