### ISSUE TITLE
Clarify Save Status

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#152]
Currently, "All Changes Saved" refers to saved to disk, in temporary Swap folder. Changes are saved to file after 15 minutes of inactivity, or on closing document. Need to clarify the save status of the file itself.

**Comment by pecefix** [comment]
"Changes saved" does not work for me at all (Version 2.4.0). Changes I made are visible as long as I do not close the file (often the Message "All changes saves" occurs, sometimes I made changes an there is still "unsaved changes" on the screen). But when I close and re-open the same file, changes are gone and I always get an old version. Am I the only one with this weird behaviour? And where can I find the temporary swap folder? Is there a chance that I can restore a file with all my changes?

**Comment by AdrianoFerrari** [comment]
That sounds pretty serious, @pecefix . Sorry about that.
I'll dig into this. In the meantime, you can find backup folder here:
* Windows : `%APPDATA%/Gingko`
* macOS : `~/Library/Application Support`
* Linux : `~/.config or $XDG_CONFIG_HOME`

**Comment by pecefix** [comment]
Thank you. I checked `%APPDATA%/Roaming/Gingko/backups/` . There are a lot of recent backups, but the files also contains old versions and not the most recent version before closing the app.  
To save recent changes I have to use `Export as (text)`. I just compared the text-file with the original gko files and they are different. It seems that the app _forgets_ after some time (or some changes) to save the new content as the first few changes are saved.

**Comment by katsumi27** [comment]
I have been having the exact same problem.
It will save at first, but after some time it will no longer save even if it says it has saved.  

The workaround I have been doing is actually exporting as JSON and then opening that file and overwriting the saved one.

**Comment by AdrianoFerrari** [comment]
I'm trying to reproduce this error so I can fix it. @katsumi27 when you say "after some time", roughly how long are you talking about? Seconds? Hours?

**Comment by AdrianoFerrari** [comment]
No need to respond, @katsumi27 . I figured out where the problem lies, and it seems to be limited to Windows. Working on a fix now.

**Comment by AdrianoFerrari** [comment]
I attempted a fix in v2.4.1.

I'd be very helpful @pecefix and @katsumi27, if you could let me know if it works as expected after auto-updating and restarting the app.

**Comment by pecefix** [comment]
Okay let's see. I tested it bit rough now, several times closing the app, moving and creating items; reloaded the file four times. With 2.4.1 I don't notice any losses yet, I'm sure that 2.4.0 would have had losses while practicing similar testing. 

But with one file (A) I have new problem now: I neither can close the file nor quit the app. And I'm not able to EXPORT the file but I can SAVE AS. 
If I open another file (B) parallel to (A), everything works with file (B) (closing, quit, export).
I had to kill the process (A) with the task manager. After opening the file (A) again, I was able to close it as usual.  

And while roughly testing I got this error twice (but without losses at the end - I was able to save it anyway): 
![2019-05-03_17h10_08](https://user-images.githubusercontent.com/39944697/57149036-28b12f00-6dcb-11e9-9ca4-f8be68d3741f.png)

And this is also interesting (*filename =/ All changes saved)
![2019-05-03_17h32_10](https://user-images.githubusercontent.com/39944697/57149099-526a5600-6dcb-11e9-9d83-624fcff0c482.png), but the * disappeared after the next editing of an item.

**Comment by katsumi27** [comment]
Did some tests: the fix seems to be working so far.

Most often it used to stop saving if I left a card opened and moved away from the program for a few minutes. But also after several minutes (40+min) of it running, it would also stop saving.

I did my best to test both of these scenarios as I'm short on time today, and it seems to be working well!


(I did have to launch the update manually from the folder though. I believe it has done a few updates automatically in the last few months, but I've never noticed it happening. This time I exited and relaunched a few times and didn't see any changes so I went looking for it so I could test.)

**Comment by pecefix** [comment]
I worked today hours with the gko-file and I confirm, that the saved file contains all the data I have created, which for sure would have not the case with 2.4.0.
I'm wondering, why the file-size of .gko is growing rapidly, while the json-file with the same content keeps really tiny?

**Comment by katsumi27** [comment]
> 
> 
> Did some tests: the fix seems to be working so far.
> 
> Most often it used to stop saving if I left a card opened and moved away from the program for a few minutes. But also after several minutes (40+min) of it running, it would also stop saving.
> 
> I did my best to test both of these scenarios as I'm short on time today, and it seems to be working well!
> 
> (I did have to launch the update manually from the folder though. I believe it has done a few updates automatically in the last few months, but I've never noticed it happening. This time I exited and relaunched a few times and didn't see any changes so I went looking for it so I could test.)

Just wanted to say that with this fix I was finally able to make some significant progress in a few projects of mine. Really grateful for Gingko!!

**Comment by AdrianoFerrari** [comment]
Thanks for the tests, and sorry again about the bug.

I'll keep this issue open, because I do still want to clarify what state of saving the app is in. At least three modes are involved:
1. Saved to temporary storage
2. ... and Saved to file
3. ... and Saved a backup

**Comment by AdrianoFerrari** [comment]
Fixed in [v2.4.2](https://github.com/gingko/client/releases/tag/v2.4.2).
