### ISSUE TITLE
Changes are cached but not saved?

### ISSUE THREAD

**Issue by cyberbryce** [gingko/client#168]
macOS version 2.4.1

Open files claim that changes are saved, but modification timestamps are suggesting otherwise. And, if you duplicate an open file, you will get an old version, not the version currently open.

I'm guessing this relates to a decision to cache the database before saving it, but it would be best--to avoid lost work--to not indicate a file as being saved (via the "lozenge" in the close button and the "All changes saved" text) until the file is actually written out to disk.

I always export anything to Markdown for further editing, so this only created an issue of lost work for me once when I duplicated a two-dimensional visual lecture outline. Gingko is a great lightweight tool for these, IMHO--and thanks for it.

**Comment by AdrianoFerrari** [comment]
Working on this as we speak :slightly_smiling_face: 
Closing as duplicate to #152 .

**Comment by cyberbryce** [comment]
Awesome! Thanks --Bryce
