### ISSUE TITLE
paragraphs spanning multiple cards

### ISSUE THREAD

**Issue by brainchild0** [gingko/client#178]
Currently, card boundaries appear to imply paragraph boundaries, but many of the benefits of card organization might be useful for segments within a paragraph.  

Perhaps a *new paragraph* flag can be added as a card attribute, such that if its disabled, the contents of the card append last paragraph represented by the previous card instead of beginning a new paragraph.  

The value of such a  flag could be represented in the display by the *new paragraph* symbol.

**Comment by AdrianoFerrari** [comment]
In my years of using Gingko, I've never found the need to rearrange segments within a paragraph in the same way that I rearrange cards. At least, not so much that just moving the text around as normal (select, cut/paste, etc) was ever a problem. I've also never had this as a feature request before, despite many others using Gingko for years as well.

I'll close this for now, because my experience and intuition is that while it might have _some_ benefit, it's likely not worth the opportunity cost of developing and supporting this feature vs others.

**Comment by brainchild0** [comment]
I understand about prioritizing.

I would only ask, what particularly do you ascribe to the paragraph boundary that makes it in some sense the lowest level of granularity for card arrangement?  

The observation that impelled me to put forward the idea was the sense that the constraint is largely arbitrary of keeping entire paragraphs on a single card, separate of course from whatever implementation costs might be incurred from removing it.

**Comment by AdrianoFerrari** [comment]
Maybe a screenshot of a particular case would help, but I can give you a quick overview of my thinking.

It isn't an entirely arbitrary place to draw the line, in my opinion. Obviously, in the hierarchy of text, being able to rearrange individual _letters_ and _words_ wouldn't be of great use. Sentences are more of a gray area, but I feel that they aren't rearranged often enough to be worth the implementation costs (to me), **or** the cognitive load *on the user* ("should I break this sentence into a different unit? Or keep it together with the paragraph?"). For that reason, I argue for drawing the line at the granularity of the paragraph (by which I mean "cohesive and somewhat self-contained unit of thought", so paragraphs *can be single sentences* if they stand alone).

More simply, if a card can't stand on its own as a unit of thought, and needs to be closer to its previous/next segments, then it's not "separate" enough to be treated as an independent unit in the UI.

Rule 8 of the "Elements of Style" states "[Make the paragraph the unit of composition](http://www.gutenberg.org/files/37134/37134-h/37134-h.htm#Rule_8)", and I think that's a very good rule.

**Comment by brainchild0** [comment]
I agree about the practical and semantic considerations, as well as the absurdity of taking card span to the lowest imaginable level or granularity.

  I mainly intended to emphasize the question of whether certain cases may benefit from an understanding of the appropriate mapping of card to semantic unit  as being less rigidly constrained. Paragraph boundaries in general writing, even well-styled writing, have a more ambiguous function than might be inferred from common contemporary examples, or from a well-regarded style guide.  Poetry might a more plain example, though not the only, of a context in which such units of demarcation function differently than some might expect.

But I respect that the overall approach is targeted toward cases that might be considered natural and typical to a general set of users.

(Strunk's principles are dear to me as having had a greater positive effect on my writing than any similarly concise doctrine, but my style in wide contexts  probably would have reached a zenith much earlier if I had kept a literal  and dogmatic adherence  to them.)
