### ISSUE TITLE
No Word Export after version 2.4.11

### ISSUE THREAD

**Issue by toppinglift** [gingko/client#196]
**Describe the bug**
After updating to versions 2.4.12 and 2.4.13, there was no Word export. The app does not save any file.
**To Reproduce**
1. Go to  File-->Export as MS Word-->Current Card and Children OR Entire Document.  Export to MS Word dialog box pops up.  Enter a file name with docx extension.
2. Click on 'Save"
3. Nothing happens--no file is saved.  This error only occurs in versions 2.4.12 and 2.4.13.  If you roll back to version 2.4.11, you can export to Word.

**Comment by afenc** [comment]
similar bugs noted here. 
In fact all export options (word, text, JSON) are not working.

Software info:
OS: [macOS 10.15.4]
Gingko Version [2.4.13.567]

**Comment by AdrianoFerrari** [comment]
Thanks for the bug reports, I wasn't aware of this and didn't come across it during testing.

@toppinglift are you on macOS as well?
Anyone else having this issue, or *not* having this issue in 2.4.12+?

**Comment by toppinglift** [comment]
My OS is Windows 10.  My gingko also updated automatically to 2.4.13.  Can we please have the option to shut down auto-update for cases like this?

**Comment by AdrianoFerrari** [comment]
Thanks for the bug reports everyone. I've uploaded a new release that should fix this.

Regarding disabling auto-updates: it's a possibility, but it's work to implement. In case of a new bug introduced with no quick fix, I can disable the version on my end, so it won't autoupdate people to the buggy version. I should have done that sooner in this case.
