### ISSUE TITLE
Add additional navigation keys, such as home, page up, etc.

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#22]
**Home**: top of column
**Page Up**: top of current group. If there already, jump up to bottom of group above.
**Page Down**: bottom of current group. If there already, jump down to top of group below.
**End**: bottom of column

**Comment by ipalindromi** [comment]
I'd like to look into this and some of the other navigation-based bugs. It seems like a good chance to learn how Elm wires things.

**Comment by AdrianoFerrari** [comment]
Great!
If you're willing to commit to getting this done, **let me know** so I can assign you to it (as a reminder that it's being worked on).

I can help anytime you get stuck.

Here's where I would start. Add this function to `Main.elm` (around [here](https://github.com/gingko/client/blob/master/src/elm/Main.elm#L774)):
```elm
goToTop : String -> ( Model, Cmd Msg ) -> ( Model, Cmd Msg )
goToTop id (model, prevCmd) =
  let
    targetId =
    -- your logic to get the first card in the column here
  in
  model ! [prevCmd]
    |> activate targetId
```

Probably simplest would be to write a `getFirstInColumn` function in `TreeUtils.elm` (around [here](https://github.com/gingko/client/blob/master/src/elm/TreeUtils.elm#L162)), using the `getPrevInColumn` function as reference (-99999 is an acceptable hack to get started).

**Comment by ipalindromi** [comment]
Yup, I'll see it through! It may take me a little longer than average, just due to building Elm knowledge.  Thanks for the context clues though, it's very helpful! I'll message back if I have any questions!

**Comment by AdrianoFerrari** [comment]
Hi @ipalindromi. Just a heads up that I'm refactoring things a little bit, so if you haven't started on this issue, it might be easier after the refactor.

If you have started though, proceed... most of the code will still be useful. It'll just have to move to a different location after refactor, most likely.

**Comment by ipalindromi** [comment]
Hey, thanks for the heads up @AdrianoFerrari! I was planning on digging into this today. I think I saw your issue regarding the refactor and was wondering if that would affect this! As I haven't started changing any actual code, I'll wait for the refactor and come back to it!

**Comment by AdrianoFerrari** [comment]
@ipalindromi , I decided to come back to the Elm refactor later, and instead focus on cleaning up the JS code and improving tests.

So if you're still interested, go ahead on this whenever you like. And as I said elsewhere: I love learning and teaching Elm, so please don't hesitate to ask me any questions during the process... it'll help *me* to help you :smile:

**Comment by ipalindromi** [comment]
Alright, I'm back on it then! I will gather up questions as I go and fling them at you liberally in the near future. :D

**Comment by ipalindromi** [comment]
@AdrianoFerrari So I'm starting with the home / end key functionality, and my first question here is that I see a command sort of similar to what I think you're suggesting exists at https://github.com/gingko/client/blob/master/src/elm/Main.elm#L635 using the alt keybinding. I could just rebind that, but my bigger question is if you have a suggestion for cleanly getting the index range of the columns rather than doing the -999999 thing. I'm trying to get my head around the data model used here, and not quite able to read it from the code yet.

**Comment by ipalindromi** [comment]
Hi @AdrianoFerrari! I got some time to look into this more this week. I have home + end figured out, at least (here's just end):
![bottom of column](https://user-images.githubusercontent.com/1351129/39952710-084756dc-556b-11e8-8bfc-45e0521dce2b.gif)

But I've run into some really weird behavior when using "home" and "end" keybinds... See here: 
![bonkers](https://user-images.githubusercontent.com/1351129/39952728-6c80e58c-556b-11e8-9786-04aee093b147.gif)

Any idea what might be causing that? I've undone all the existing bindings that might interfere (that I can see) but something else seems to be at play.

Thanks! In the meanwhile, I'll start looking into Page Up / Page Down.

**Comment by ipalindromi** [comment]
Immediately after I posted this I figured out at least some of the issue, which is that "home" and "end" were not being explicitly set in `shared.js`. With that set, the issue doesn't seem to manifest. 

So this may be a non-issue, but still... It would be interesting to know what causes that jumping behavior.

**Comment by AdrianoFerrari** [comment]
Thanks for working on this! That's happening because the "home" and "end" keys are also triggering the default behavior for the scrolling element (even though you can't see the scrollbars, each column is actually just a div with `overflow-y: scroll`).

To fix this, just add "home" and "end" to the `needOverride` array as well, here:
https://github.com/gingko/client/blob/master/src/shared/shared.js#L279

That prevents the default action from happening by doing `return false` [here](https://github.com/gingko/client/blob/master/src/shared/main.js#L999). Doing `return false` is the way that Mousetrap (the utility used for keyboard bindings) prevents the default action: https://craig.is/killing/mice#api.bind.default

**Comment by AdrianoFerrari** [comment]
By the way, you can submit a Pull Request, even if it's you're not ready to merge. That way I can see the code you're working on and help out where needed.

I didn't know this when I started open source, but once you create a pull request, any time you make a commit to the same branch it updates the PR... so that means you can open a PR before you're ready, and simply push to it as you work. Nice way to share your work in progress and get feedback, I think :slightly_smiling_face:

**Comment by ipalindromi** [comment]
It's my pleasure! Getting going on it was a bit frustrating, but I can _almost_ read Elm now, so things are flowing much more smoothly. :D 

That PR idea is great, I had no idea it worked like that! I'll get one prepped and up later today. Feedback will be very valuable.
