### ISSUE TITLE
Switch from AppImage to Snap?

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#31]
Pros for switch:
* electron-builder now defaults to Snap
* Snap has auto-updates built in

Cons:
* Dblsqd and its interface won't work with Snap
* Current users with AppImage won't receive update notifications

**Comment by probonopd** [comment]
Please continue to provide AppImages.

Providing an [AppImage](http://appimage.org/) has, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by AdrianoFerrari** [comment]
Hi @probonopd .

I like AppImage, a lot, and prefer it to the other options. I've decided to keep it as the only Linux target for now.

For me, the ideal user-facing solution for updating apps, is as follows:
1. User can download a version of my app.
2. User can easily install it (arugably, "make executable" is one additional step, but likely an easy one for linux users).
2. User gets notified in-app (optionally, on-by-default), when an update is available.
3. Notification includes Changelog(s) from current version.
4. User can one-click upgrade to newest version, by downloading binary delta.

Now, even though it seems that all this *can* be done with AppImage, so far I am developing this on my own. I hope I won't have to make the switch to Snap later, but if it makes my own build and *update* process simpler, I'll have to do so.
