### ISSUE TITLE
Highlight parent card

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#52]
**Current**: Parent card has no special formatting.

**Desired**: Like web version, parent card stands out somewhat from its siblings.

**Comment by AdrianoFerrari** [comment]
Policy: Issues should be closed when *released*, not just when committed.

**Comment by AdrianoFerrari** [comment]
Fixed in v2.0.7.

**Comment by gottlike** [comment]
@AdrianoFerrari Thanks for implementing! I noticed, however, that only the direct parent of the currently active card is highlighted - not the whole tree. This helps slightly, but is still rather confusing, when you have tree deeper than 2 cards. Maybe you will reconsider closing this issue?

**Comment by AdrianoFerrari** [comment]
Thanks yes I am aware. I'll open a separate issue for that... highlighting parent was a quicker fix, but I agree that setting the whole path is important.
